name = "duckdb"
version = "0.1.0"
license = "license"
author = "Andre Smit"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2023, Andre Smit"

executable = [
  { name = "main", main = "main.f90"},
  { name = "test", main = "test.c"}
]

[build]
link = ["duckdb"]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
