name = "duckdb"
version = "0.1.0"
license = "MIT"
author = "Andre Smit, Ludovico Nicotina"
maintainer = "freevryheid@gmail.com"
copyright = "Copyright 2023, Andre Smit"

[build]
link = ["duckdb"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dev-dependencies]
test-drive.git = "https://github.com/fortran-lang/test-drive"
# stdlib = { git="https://github.com/fortran-lang/stdlib", branch="stdlib-fpm" }

